#+Title: Introduction to Ansible
#+Date: <2016-04-21 Thu>
#+Author: Yogesh Agrawal
#+Email: yogeshiiith@gmail.com; yogesh@vlabs.ac.in


* Introduction
  This document describes Ansible.

* Concepts
  - Ansible is agentless, there is no agent running on the systems we
    control.
  - Ansible can manage thousands of nodes.
  - Ansible uses SSH protocol.

* Key components
  - Inventory :: hosts, instances
  - Modules/Tasks :: cloud, command
  - Plays :: blocks of things to do
  - Playbooks :: plays are part of playbooks

** Inventory
  Inventory consists of:
  - hosts :: hosts can be individual host or a group of hosts.
    #+BEGIN_EXAMPLE
    - hosts:
    webservers
    - hosts:
    127.0.0.1
    #+END_EXAMPLE

  - inventory specific data :: variables can be defined at multiple
       places.
    #+BEGIN_EXAMPLE
    http_port:
    max_clients:
    #+END_EXAMPLE
  
  - Modules ::
    #+BEGIN_EXAMPLE
    apt, copy, ec2, file, service, template, user
    #+END_EXAMPLE

** Modules
  1. Using modules in tasks
     #+BEGIN_EXAMPLE
     - name: add cache dir
       file: path=/opt/cache state=directory
     - name: install nginx
       yum: name=nginx state=present
     - name: start nginx
       service: name=nginx enabled=yes state=started
     #+END_EXAMPLE
  2. raw module can be used to run ssh commands which does not have
     python installed. We can use this also for bootstrapping instance
     with python.

* Ad-Hoc commands
  1. adhoc command to check uptime of the systems.
     #+BEGIN_EXAMPLE
     ansible localhost -m command -a "uptime"
     #+END_EXAMPLE

* Examples
