#+Title: DNS
#+Author: Yogesh Agrawal
#+Email: yogeshiiith@gmail.com
#+Date: <2016-06-06 Mon>

* Introduction
  This guide describes the dns.

* DNS Terminology
  |-----------------------------+----------------------------------------------|
  | *Term                       | Definition and Usage*                        |
  |-----------------------------+----------------------------------------------|
  | Domain Name                 | A Domain Name has a registered owner         |
  |                             | and the owner is authoritative and           |
  |                             | responsible for DNS information.             |
  |-----------------------------+----------------------------------------------|
  | Fully Qualified Domain Name | Defines a domain name to the root.           |
  | (FQDN)                      | A FQDN must therefore include the root       |
  |                             | which in turn means it must have a           |
  |                             | final DOT on the extreme right of the        |
  |                             | domain name. For example                     |
  |                             | www.example.com. is a FQDN whereas           |
  |                             | www.example.com is not (it does not          |
  |                             | terminate with a DOT)                        |
  |-----------------------------+----------------------------------------------|
  | host name                   | Fully defines a host within a domain,        |
  |                             | for example, fred.example.com is a host      |
  |                             | name.                                        |
  |-----------------------------+----------------------------------------------|
  | sub-domain name             | A sub-domain name will fully include         |
  |                             | the Domain Name us.example.com is a valid    |
  |                             | sub-domain name of example.com               |
  |-----------------------------+----------------------------------------------|
  | Zone Name                   | Any part of a domain that is configured      |
  |                             | in a DNS server and which fully contains     |
  |                             | the Domain Name for which the owner is       |
  |                             | authoritative, for instance example.com,     |
  |                             | us.example.com are Zone names. A zone is     |
  |                             | an operational convenience for DNS software  |
  |                             | and not part of the domain naming hierarchy. |
  |-----------------------------+----------------------------------------------|

* Name Server
  As our network grows we start to build up a serious number of Names
  in our Name Server (database). This gives rise to following three
  problems:
  1. Lot of names - Searching becomes slow.
  2. All the queries come to single name server, load becomes very high.
  3. Administration and updation of entries becomes difficult.

* DNS concepts and implementation
  The Internet's Domain Name Service (DNS) is just a specific
  implementation of the Name Server concept optimized for the
  prevailing conditions on the internet.

  From the brief history of name servers following three needs
  emerged:
  1. The need for a hierarchy of names.
  2. The need to separate operational loads on our name servers.
  3. The need to delegate the administration of our name servers.

  The Internet Domain Name System elegantly solves all these problems
  [[https://tools.ietf.org/html/rfc1035][(RFC 1034)]]. 

** Domains and Delegation
   The Domain Name System uses a tree (or hierarchical) name
   structure. At the top of the tree is the root followed by the Top
   level Domains (TLDs) then the domain-name and any number of lower
   levels each separated with a dot.

*** Authority and Delegation
    The concepts of Delegation and Authority lies at the core of the
    domain name system hierarchy. The authority of the root domain
    lies with (ICANN). The generic top level domains are
    authoritatively administered by ICANN and delegated to a series of
    accredited registrars.

    Consider following example:
    #+BEGIN_EXAMPLE
    www.us.example.com
    #+END_EXAMPLE
    Its domain name is =example.com=, =www= probably indicates a web
    site.
    
    The owner can delegate, in any way they want, anything to the left
    of the domain name they own. The owner is also responsible for
    administering this delegation which means running, or delegating
    the task of running, a DNS containing Authoritative information
    (or records) for their Domain Name (or zone).
** DNS Organization and structure
   There are currently 13 [[http://www.root-servers.org/][root-servers world wide]]. The root servers
   are known to every public DNS server in the world and are starting
   point for every name lookup operation. To create resilience each
   root-server typically has multiple instances (copies) spread
   throughout the world. Each instance has the same ip address but the
   data is sent to the closest instance using a process called
   *anycasting.*

   When any DNS cannot answer (resolve) a request (a query) for a
   domain name from a client, for instance, example.com, the query is
   passed to a root-server which will direct (refer) the query to the
   appropriate TLD DNS server (for .com) which will in turn direct
   (refer) it to the appropriate Domain (User) DNS server.

** DNS System Components
   A Domain Name System (DNS) includes three parts:
   1. Data which describes the domain(s).
   2. One or more Name Server programs.
   3. A resolver program or library.

   A single DNS server may support many domains. The data for each
   domain describes global properties of the domain and its hosts (or
   services). This data is defined in the form of textual resource
   records organized in zone files. The format of zone file is defined
   in RFC 1035 and is supported by most DNS software.

* Questions
  1. What is the significance of non-authoritative name server.
  2. =/var/named/named.ca= contains the root name servers.
