#+Title: Network File System
#+Author: Yogesh Agrawal
#+Date: <2016-06-08 Wed>
#+Email: yogeshiiith@gmail.com

* Introduction
  This document describes about the network file system.

* NFS
  A Network File System (NFS) allows remote hosts to mount file
  systems over a network and interact with those file systems as
  though they are mounted locally.

* Communication Protocol
  NFS can use Transmission Control Protocol (TCP) running over an IP
  network. NFS can also use the User Datagram Protocol (UDP) running
  over an IP network to provide stateless network connection between
  the client and server.

** UDP vs TCP
   Using NFS with UDP under normal conditions has less Protocol
   overhead than TCP which can translate into better performance on
   clean, non-congested networks. However, if the server goes down
   unexpectedly, UDP clients continue to saturate the network with
   requests for the server. For this reason TCP is preferred protocol
   when connecting to an NFS server.

   NFSv4 listens on the well known TCP port (2049).

   - Note :: TCP is the default transport protocol for NFS. UDP can be
             used compatibility purposes as needed, but it is not
             recommended for wide usage. All the RPC/NFS daemon have a
             '-p' command line option that can set the port, making
             firewall configuration easier.

** NFS Port
   In order for NFS to work with a default installation, IPTables with
   the default TCP port 2049 must be configured. Without proper
   IPTables configuration, NFS does not function properly.
* Required Services
  NFS relies on Remote Procedure Calls (RPC) between client and
  servers. RPC services under Linux are controlled by *portmap*
  service. To share or mount NFS file systems, the following services
  work together, depending on which version of NFS is implemented.

** nfs - (/sbin/service nfs start)
   starts the NFS server and the appropriate RPC processes to service
   requests for shared NFS file systems.

** nfslock - (/sbin/service nfslock start)
   It is a mandatory service that starts the appropriate RPC processes
   to allows NFS clients to lock files on the server.

** portmap
   It accepts port reservations from local RPC services. These ports
   are then made available so the corresponding remote RPC services
   access them. *portmap* responds to requests for RPC services and
   sets up connections to the requested RPC service.
* NFS Client Configuration
  NFS shares are mounted on the client side using the *mount*
  command.
  #+BEGIN_EXAMPLE
  mount -t <nfs-type> -o <options> <host>:</remote/export> </local/directory>
  #+END_EXAMPLE
  - <nfs-type> : nfs or nfs4
  - <options> : comma separated list of options
  - <host> : remote host
  - </remote/export> : remote directory being mounted
  - </local/directory> : local directory where the remote file system
    is to be mounted. 

** Mounting NFS File Systems using /etc/fstab
   To mount an NFS share from another machine is to add a line to the
   =/etc/fstab= file.
   #+BEGIN_EXAMPLE
   <server>:</remote/export> </local/directory> <nfs-type> <options> 0 0
   #+END_EXAMPLE
   #+BEGIN_EXAMPLE
   server:/usr/local/pub    /pub   nfs    rsize=8192,wsize=8192,timeo=14,intr
   #+END_EXAMPLE
   The mount point =/pub= must exist on the client machine before this
   command can be executed. After adding this line to =/etc/fstab= on
   the client system, type the command =mount /pub= at a shell prompt,
   and the mount point =/pub= is mounted from the server.
