#+Title: Site Reliability Engineering
#+Author: Yogesh Agrawal
#+Date: <2016-05-09 Mon>
#+Email: yogeshiiith@gmail.com

* Introduction
  This document describes the learnings from reading of the book *site
  reliability engineering - Google*.

* SRE Definition
  SRE are engineers: apply principles of computer science and
  engineering to build complex and distributed systems.

* Reliability
  Reliability is the probability that a system will perform a required
  function without failure under stated conditions for a state period
  of time.

  Reliability is the most fundamental feature of any product. From all
  the post deployment characteristics of a software that we could
  choose to devote special attention to, the reliability is one we
  regard as primary.

* SRE principle
  Thoroughness and dedication, belief in the value of preparation and
  documentation, and an awareness of what could go wrong, coupled with
  a strong desire to prevent it.

* System Administrator
  The system administrator involves assembling existing software
  components and deploying them to work together to produce a service.

  We need systems that are automati,c not just automated.

* Tenets of SRE
  A SRE team is responsible for the availability, latency,
  performance, efficiency, change management, monitoring, emergency
  response, and capacity planning of the service(s).

  Postmortems should be written for all significant incidents,
  regardless of whether or not they paged; postmortems that did not
  trigger a page are even more valuable, as they likely point to clear
  monitoring gaps. This investigation should establish what happened
  in detail, find all root causes of the event, and assign actions to
  correct the problem or improve how it is addressed next time. The
  goal should be to fix these faults, rather than avoiding or
  minimizing them.

* TODO
  1. Translate the text - "Google grew at a time when the traditional
     role of the system administrator was being transformed."

