#+Title: Site Reliability Engineering
#+Author: Yogesh Agrawal
#+Date: <2016-05-09 Mon>
#+Email: yogeshiiith@gmail.com

* Introduction
  This document describes the learnings from reading of the book *site
  reliability engineering - Google*.

* SRE Definition
  SRE are engineers: apply principles of computer science and
  engineering to build complex and distributed systems.

* Reliability
  Reliability is the probability that a system will perform a required
  function without failure under stated conditions for a state period
  of time.

  Reliability is the most fundamental feature of any product. From all
  the post deployment characteristics of a software that we could
  choose to devote special attention to, the reliability is one we
  regard as primary.

* SRE principle
  Thoroughness and dedication, belief in the value of preparation and
  documentation, and an awareness of what could go wrong, coupled with
  a strong desire to prevent it.

  Common to all SREs is the belief in and aptitude for developing
  software systems to solve complex problems.

* TODO
  1. Translate the text - "Google grew at a time when the traditional
     role of the system administrator was being transformed."

