#+Title: Unix Administration Guide
#+Author: Yogesh Agrawal
#+Date: <2016-11-27 Sun>

* Introduction
  This document describes the unix administration guide.

* System administrator responsibilities
  - Routine backup of filesystem
  - Reading root's mail
  - Writing scripts
  - Maintain logbook or documentation

* System Device Directory
  Device directory in UNIX systems - =/dev=, holds from 30 to several
  hundreds entries each making a potential connection between some
  piece of hardware and the file system.

* Basic Terminology
** Kernel
   Kernel or operating system "program", gets loaded into computer
   during startup and stays in memory. The kernel manages the system
   hardware, that is, the memory, disks, and communications.

** System Call
   When a user programs want to execute any privileged programs, it
   invokes system call which request the kernel to do the defined
   task.

** Process
   A process is a program in execution. Kernel loads the program into
   memory as the result of an exec (execute) system call. The process
   may freely read or write its own data, but must make system calls
   to read or write to the file system, or do anything beyond
   manipulating its memory space.


* References
  - https://www.amazon.com/Unix-Administration-Guide-System-V/dp/0139428895
