#+Title: Private DNS using bind
#+Author: Yogesh Agrawal
#+Date: <2016-12-20 Tue>
#+Email: yogesh.agrawal@capitalfloat.com

* Introduction
  Setup private bind dns server.

* Installation
  #+BEGIN_EXAMPLE
  sudo apt-get install bind9 bind9utils bind9-doc
  #+END_EXAMPLE
  
* Configuration Scenarios
  BIND9 can provide many different DNS services.

** Caching Server
   In this configuration BIND9 will find answer to name queries and
   remember the answer for the next query. This can be useful for slow
   internet connection. By caching DNS queries, we will reduce
   bandwidth and (more importantly) latency.

** Primary Master Server
   BIND9 can be used to serve DNS records (groups of records are
   referred to as zones) for a registered domain name or an imaginary
   one (but only if used on a restricted network).

** Secondary Master Server
   A secondary master DNS server is used to complement a primary
   master DNS server by serving a copy of the zone(s) configured on
   the primary server. Secondary servers are recommended in larger
   setups. If we intend to serve a registered domain name then ensure
   that DNS zone is still available even if our primary server is not
   online.

* References
  - https://help.ubuntu.com/community/BIND9ServerHowto
  - https://www.digitalocean.com/community/tutorials/how-to-configure-bind-as-a-private-network-dns-server-on-ubuntu-14-04 
