#+Title: Private DNS using bind
#+Author: Yogesh Agrawal
#+Date: <2016-12-20 Tue>
#+Email: yogesh.agrawal@capitalfloat.com

* Introduction
  Setup private bind dns server.

* Installation
  #+BEGIN_EXAMPLE
  sudo apt-get install bind9 bind9utils bind9-doc
  #+END_EXAMPLE
  
* Configuration Scenarios
  BIND9 can provide many different DNS services.

** Caching Server
   In this configuration BIND9 will find answer to name queries and
   remember the answer for the next query. This can be useful for slow
   internet connection. By caching DNS queries, we will reduce
   bandwidth and (more importantly) latency.

** Primary Master Server
   BIND9 can be used to serve DNS records (groups of records are
   referred to as zones) for a registered domain name or an imaginary
   one (but only if used on a restricted network).

** Secondary Master Server
   A secondary master DNS server is used to complement a primary
   master DNS server by serving a copy of the zone(s) configured on
   the primary server. Secondary servers are recommended in larger
   setups. If we intend to serve a registered domain name then ensure
   that DNS zone is still available even if our primary server is not
   online.

* DNS Record Types
** Address Records
   This record maps an IP Address to a hostname.
   #+BEGIN_EXAMPLE
   www IN A 1.2.3.4
   #+END_EXAMPLE
** Alias Records
   Used to create alias from an existing A record. We can create a
   CNAME record pointing to another CNAME record. But it doubles the
   number of requests made to the nameserver, thus making it an
   inefficient way to do so.
   
   #+BEGIN_EXAMPLE
   mail IN CNAME www
   www IN A 1.2.3.4
   #+END_EXAMPLE
   
** Mail Exchange Records
   Used to specify where email should be sent to and at what
   priority. Must point to an A record, not a CNAME. Multiple MX
   records can exist if multiple mail servers are responsible for that
   domain.
   #+BEGIN_EXAMPLE
        IN MX 10 mail.example.com.
   mail IN A 1.2.3.4
   #+END_EXAMPLE

** Name Server Records
   Used to define which servers serve copies of this zone. It must
   point to an A record, not a CNAME. This is where Primary and
   Secondary servers are defined.
   #+BEGIN_EXAMPLE
           IN    NS     ns.example.com.

        [...]

   ns      IN    A      1.2.3.4
   #+END_EXAMPLE

* Configuring BIND9
  - Configuration files are stored in:
    #+BEGIN_EXAMPLE
    /etc/bind
    #+END_EXAMPLE
    #+BEGIN_EXAMPLE
    /etc/bind/named.conf
    /etc/bind/named.conf.options
    /etc/bind/named.conf.local
    #+END_EXAMPLE
* Caching Server Configuration
  The default configuration is setp to act as a caching server. All
  that is required is simply adding the IP numbers of the ISP's DNS
  servers.

  We need to uncomment and edit following in
  =/etc/bind/named.conf.options=:
  #+BEGIN_EXAMPLE
          [...]

        forwarders {
             1.2.3.4;
             5.6.7.8;
        };

        [...]
  #+END_EXAMPLE

  Now restart the bind daemon:
  #+BEGIN_EXAMPLE
  sudo /etc/init.d/bind9 restart
  #+END_EXAMPLE

* Primary Master Server Configuration
  In this section BIND9 will be configured as the primary master for
  the domain =example.com=. We can replace example.com with our fully
  qualified domain name.

** Zone file
   To add a dns zone to BIND9, turning BIND9 into a Primary Master
   server, we have to edit =named.conf.local= as follows:
   #+BEGIN_EXAMPLE
           [...]

        zone "example.com" {
             type master;
             file "/etc/bind/db.example.com";
        };

        [...]
   #+END_EXAMPLE

   Now we can use the existing zone file as a template:
   
   #+BEGIN_EXAMPLE
   sudo cp /etc/bind/db.local /etc/bind/db.example.com
   #+END_EXAMPLE

   Edit the new zone file /etc/bind/db.example.com change =localhost.=
   to the FQDN of our server. Leaving the additional "." at the
   end. Change =127.0.0.1= to the nameserver's IP Address and
   root.localhost to a valid email address, but with a "." instead of
   the "@", also leaving "." at the end.

   Also, create an =A record= for ns.example.com the name server.

   #+BEGIN_EXAMPLE
   ;
   ; BIND data file for local loopback interface
   ;
   $TTL    604800
   @       IN      SOA     ns.example.com. root.example.com. (
                              1         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
   ;
   @       IN      NS      ns.example.com.
   ns      IN      A       192.168.1.10
   
   ;also list other computers
   box     IN      A       192.168.1.21
   #+END_EXAMPLE

   We must increment the serial number every time we make changes to
   the zone file.

   *Tip:* Many people like to use last date edited as the serial
   number yyyymmddss (where s is serial), as the serial number.
   
   Once we have made any changes to the dns zone file, it will require
   restart:
   #+BEGIN_EXAMPLE
   sudo /etc/init.d/bind9 restart
   #+END_EXAMPLE
   
* References
  - https://help.ubuntu.com/community/BIND9ServerHowto
  - https://www.digitalocean.com/community/tutorials/how-to-configure-bind-as-a-private-network-dns-server-on-ubuntu-14-04 
  - http://www.tldp.org/HOWTO/DNS-HOWTO-7.html
  - http://dyn.com/blog/recursive-dns-how-does-it-work/
  - https://kb.isc.org/article/AA-00269/0/What-has-changed-in-the-behavior-of-allow-recursion-and-allow-query-cache.html
  - http://www.zytrax.com/books/dns/ch7/queries.html#allow-recursion
