#+Title: Nginx
#+Author: Yogesh Agrawal
#+Email: yogeshiiith@gmail.com
#+Date: <2016-06-28 Tue>

* Introduction
  This document discusses about the concepts of Nginx.

* Errors
** 4xx Client Error
** 5xx Server Error
   Response status codes beginning with the digit "5" indicates cases
   in which the server is aware that it is incapable of performing
   the request.

*** 502 Bad Gateway
    What does this error message means ? A gateway is like an access
    point, a bridge that communicates one service with another. The
    server was acting as a gateway or proxy and received an invalid
    response from the upstream server.

    Nginx 502 Bad Gateway error message:
    1. PHP daemon stop working, or get's overloaded by requests, it
       will not work properly and all the requests from nginx would
       not be served, so, a 502 Bad Gateway error will appear.

    2. Increase buffer and timeouts inside http block.

**** Possible solutions
     1. Is PHP-FPM running ?
        #+BEGIN_EXAMPLE
	ps aux | grep php
	sudo service php5-fpm restart/stop/start
	#+END_EXAMPLE

     2. Is PHP-FPM listening correctly ?
	
	Ensure =listen= parameter in =/etc/php5/fpm/pool.d/www.conf=
	and =fastcgi_pass= parameter in =/etc/nginx/sites-available=
        are set to the same value as follows:
	#+BEGIN_EXAMPLE
	127.0.0.1:9000
	#+END_EXAMPLE

**** References
     - https://www.keycdn.com/support/502-bad-gateway/
     - http://jvdc.me/fix-502-bad-gateway-error-on-nginx-server-after-upgrading-php/
