---
- name: install apache package
  hosts: webservers
  sudo: true

  tasks:
    - name: install apache
      apt: name=apache state=present

    - name: start and enable apache
      service: name=apache enabled=yes state=started  