---
- name: install apache package
  hosts: localhost
  sudo: true

  tasks:
    - name: install apache
      apt: name=apache state=present

    - name: start
      service: name=apache state=started  